default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: pois_development

test:
  <<: *default
  database: pois_test

production:
  <<: *default
  username: pois
  database: pois_production
  password: <%= ENV['POIS_DATABASE_PASSWORD'] %>
